// Copyright (c) 2025 ynet Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	handler "github.com/coze-dev/coze-loop/backend/api/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	// /metrics 由 sidecar HTTP server 提供（在 startMetricsServer 中），
	// 因为在 Hertz 这里注册多个 r.GET 时，generated Register 的 r.Group 似乎覆盖了它们
}
