// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/rpc (interfaces: IWorkflowProvider)
//
// Generated by this command:
//
//	mockgen -destination=modules/observability/domain/component/rpc/mocks/workflow.go -package=mocks github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/rpc IWorkflowProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	loop_span "github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/entity/loop_span"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkflowProvider is a mock of IWorkflowProvider interface.
type MockIWorkflowProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowProviderMockRecorder
	isgomock struct{}
}

// MockIWorkflowProviderMockRecorder is the mock recorder for MockIWorkflowProvider.
type MockIWorkflowProviderMockRecorder struct {
	mock *MockIWorkflowProvider
}

// NewMockIWorkflowProvider creates a new mock instance.
func NewMockIWorkflowProvider(ctrl *gomock.Controller) *MockIWorkflowProvider {
	mock := &MockIWorkflowProvider{ctrl: ctrl}
	mock.recorder = &MockIWorkflowProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowProvider) EXPECT() *MockIWorkflowProviderMockRecorder {
	return m.recorder
}

// BatchGetWorkflows mocks base method.
func (m *MockIWorkflowProvider) BatchGetWorkflows(ctx context.Context, spans loop_span.SpanList) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetWorkflows", ctx, spans)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetWorkflows indicates an expected call of BatchGetWorkflows.
func (mr *MockIWorkflowProviderMockRecorder) BatchGetWorkflows(ctx, spans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetWorkflows", reflect.TypeOf((*MockIWorkflowProvider)(nil).BatchGetWorkflows), ctx, spans)
}
